services:
  # A web service
  - type: web
    name: product-catalog-query-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false # This means it's a secret and won't be stored in the repo
