services:
  # A Docker web service
  - type: web
    name: product-catalog-query-engine
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: OPENAI_API_KEY
        sync: false # This means it's a secret and won't be stored in the repo
